import {
	Organization,
	MinistryEvent,
	Ministry,
	Team,
	Role,
	Requirement,
	User,
	Experience,
	Thread,
	Message,
	RoleOptions,
	TypeOptions,
} from './types';

type DBSchema = {
	organizations: Organization[];
	events: MinistryEvent[];
	ministries: Ministry[];
	teams: Team[];
	roles: Role[];
	requirements?: Requirement[];
	users: User[];
	experiences: Experience[];
	threads?: Thread[];
	messages?: Message[];
};

const DB: DBSchema = {
	organizations: [
		{
			id: 1,
			name: 'Community Church',
			description: 'A welcoming church serving the local community.',
			address: '123 Main Street, Anytown, USA',
			seniorPastor: 1, // Assuming user_id for the senior pastor
			logo: '/public/img/organization_logo.jpg',
			website: 'https://www.communitychurch.org',
			brandColors: ['#3498db', '#e74c3c', '#2ecc71'],
		},
	],
	events: [
		{
			id: 1,
			title: 'Sunday Morning Worship Service',
			description: 'Join us every Sunday for a vibrant worship experience.',
			date: '',
			time: '',
			ministries: [1],
		},
	],
	ministries: [
		{
			id: 1,
			title: 'Worship Ministry',
			description: 'The worship team leads us in praise and worship to God',
			logo: '/public/img/worship-service-logo.jpg',
			bannerImage: '/public/img/worship-service-banner.jpg',
			teams: [1, 2],
		},
	],
	teams: [
		{
			id: 1,
			title: 'Worship Team',
			roles: [1, 2, 3], // Assuming role_id(s) for members of the worship team
			teamLead: 1, // Assuming user_id for the team lead
		},
		{
			id: 2,
			title: 'Front of House',
			description:
				'FOH handles audio and lighting engineering, as well as managing slides',
			roles: [4, 5, 6], // Assuming role_id(s) for members of the front of house team (e.g., sound and lighting technicians)
			requirements: [1], // Assuming requirement_id(s) for specific requirements (e.g., sound equipment setup)
			teamLead: 2, // Assuming user_id for the team lead
		},
	],
	roles: [
		{
			id: 1,
			type: TypeOptions.BandVocalsLead,
			description: 'Lead vocalist',
			experienceRequired: 3,
		},
		{
			id: 2,
			type: TypeOptions.BandGuitarLead,
			description: 'Lead guitarist',
			experienceRequired: 3,
		},
		{
			id: 3,
			type: TypeOptions.BandKeys,
			experienceRequired: 3,
		},
		{
			id: 4,
			type: TypeOptions.TechAudio,
			description: 'Audio engineer',
			experienceRequired: 2,
		},
		{
			id: 5,
			type: TypeOptions.TechLighting,
			description: 'Lighting engineer',
			experienceRequired: 3,
		},
		{
			id: 6,
			type: TypeOptions.TechSlides,
			description: 'Controls slides throughout service for worship and sermon',
			experienceRequired: 2,
		},
	],
	users: [
		{
			id: 1,
			firstName: 'John',
			lastName: 'Doe',
			role: RoleOptions.Volunteer,
			address: '123 Main St',
			city: 'Anytown',
			state: 'CA',
			zip: '12345',
			email: 'john@example.com',
			password: 'password123',
			phone: '555-555-5555',
			profilePhoto: '/public/img/profile-pics/man-1.jpg',
			preferredNumWeeksServing: 3,
			experiences: [1, 2], // IDs of previous experiences
		},
		{
			id: 2,
			firstName: 'Alice',
			lastName: 'Smith',
			role: RoleOptions.Volunteer,
			address: '456 Elm St',
			city: 'Smallville',
			state: 'NY',
			zip: '54321',
			email: 'alice@example.com',
			password: 'password456',
			phone: '555-555-5556',
			profilePhoto: '/public/img/profile-pics/woman-1.jpg',
			preferredNumWeeksServing: 2,
			experiences: [3], // IDs of previous experiences
		},
		{
			id: 3,
			firstName: 'Michael',
			lastName: 'Johnson',
			role: RoleOptions.Volunteer,
			address: '789 Oak Ave',
			city: 'Hometown',
			state: 'TX',
			zip: '98765',
			email: 'michael@example.com',
			password: 'password789',
			phone: '555-555-5557',
			profilePhoto: '/public/img/profile-pics/man-2.jpg',
			preferredNumWeeksServing: 1,
		},
		{
			id: 4,
			firstName: 'Sarah',
			lastName: 'Brown',
			role: RoleOptions.Volunteer,
			email: 'sarah@example.com',
			password: 'password890',
			phone: '555-555-5558',
			preferredNumWeeksServing: 4,
			experiences: [4, 5, 6], // IDs of previous experiences
		},
		{
			id: 5,
			firstName: 'David',
			lastName: 'Wilson',
			role: RoleOptions.Volunteer,
			email: 'david@example.com',
			password: 'password901',
			profilePhoto: '/public/img/profile-pics/man-12.jpg',
			preferredNumWeeksServing: 2,
			experiences: [7, 8], // IDs of previous experiences
		},
		{
			id: 6,
			firstName: 'Emily',
			lastName: 'Davis',
			role: RoleOptions.Volunteer,
			email: 'emily@example.com',
			password: 'password234',
			phone: '555-555-5559',
			profilePhoto: '/public/img/profile-pics/woman-12.jpg',
			preferredNumWeeksServing: 3,
		},
		{
			id: 7,
			firstName: 'James',
			lastName: 'Clark',
			role: RoleOptions.Volunteer,
			email: 'james@example.com',
			password: 'password567',
			phone: '555-555-5560',
			preferredNumWeeksServing: 2,
			experiences: [9], // IDs of previous experiences
		},
		{
			id: 8,
			firstName: 'Olivia',
			lastName: 'Martinez',
			role: RoleOptions.Volunteer,
			email: 'olivia@example.com',
			password: 'password890',
			phone: '555-555-5561',
			profilePhoto: '/public/img/profile-pics/woman-13.jpg',
			preferredNumWeeksServing: 4,
			experiences: [10], // IDs of previous experiences
		},
		{
			id: 9,
			firstName: 'Liam',
			lastName: 'Lee',
			role: RoleOptions.Volunteer,
			email: 'liam@example.com',
			password: 'password123',
			profilePhoto: '/public/img/profile-pics/man-13.jpg',
			preferredNumWeeksServing: 1,
			experiences: [11], // IDs of previous experiences
		},
		{
			id: 10,
			firstName: 'Ava',
			lastName: 'Garcia',
			role: RoleOptions.Volunteer,
			email: 'ava@example.com',
			password: 'password456',
			phone: '555-555-5562',
			profilePhoto: '/public/img/profile-pics/woman-17.jpg',
			preferredNumWeeksServing: 2,
		},
		{
			id: 11,
			firstName: 'Robert',
			lastName: 'Turner',
			role: RoleOptions.Volunteer,
			email: 'robert@example.com',
			password: 'password789',
			profilePhoto: '/public/img/profile-pics/man-14.jpg',
			preferredNumWeeksServing: 3,
			experiences: [12, 13, 14], // IDs of previous experiences
		},
		{
			id: 12,
			firstName: 'Sophia',
			lastName: 'Hernandez',
			role: RoleOptions.Volunteer,
			email: 'sophia@example.com',
			password: 'password123',
			phone: '555-555-5563',
			profilePhoto: '/public/img/profile-pics/woman-21.jpg',
			preferredNumWeeksServing: 2,
			experiences: [15], // IDs of previous experiences
		},
		{
			id: 13,
			firstName: 'William',
			lastName: 'Scott',
			role: RoleOptions.Volunteer,
			email: 'william@example.com',
			password: 'password456',
			preferredNumWeeksServing: 1,
			experiences: [16], // IDs of previous experiences
		},
		{
			id: 14,
			firstName: 'Ella',
			lastName: 'Adams',
			role: RoleOptions.Volunteer,
			email: 'ella@example.com',
			password: 'password890',
			phone: '555-555-5564',
			profilePhoto: '/public/img/profile-pics/woman-23.jpg',
			preferredNumWeeksServing: 4,
			experiences: [17], // IDs of previous experiences
		},
		{
			id: 15,
			firstName: 'Michael',
			lastName: 'Baker',
			role: RoleOptions.Volunteer,
			email: 'michael@example.com',
			password: 'password901',
			preferredNumWeeksServing: 2,
			experiences: [18], // IDs of previous experiences
		},
		{
			id: 16,
			firstName: 'Grace',
			lastName: 'Lewis',
			role: RoleOptions.Volunteer,
			email: 'grace@example.com',
			password: 'password234',
			phone: '555-555-5565',
			profilePhoto: '/public/img/profile-pics/woman-22.jpg',
			preferredNumWeeksServing: 3,
		},
		{
			id: 17,
			firstName: 'Daniel',
			lastName: 'Green',
			role: RoleOptions.Volunteer,
			email: 'daniel@example.com',
			password: 'password567',
			profilePhoto: '/public/img/profile-pics/man-18.jpg',
			preferredNumWeeksServing: 2,
		},
		{
			id: 18,
			firstName: 'Mia',
			lastName: 'Lopez',
			role: RoleOptions.Volunteer,
			email: 'mia@example.com',
			password: 'password890',
			phone: '555-555-5566',
			profilePhoto: '/public/img/profile-pics/woman-8.jpg',
			preferredNumWeeksServing: 4,
		},
		{
			id: 19,
			firstName: 'Ethan',
			lastName: 'King',
			role: RoleOptions.Volunteer,
			email: 'ethan@example.com',
			password: 'password123',
			profilePhoto: '/public/img/profile-pics/man-16.jpg',
			preferredNumWeeksServing: 1,
			experiences: [19, 20, 21, 22], // IDs of previous experiences
		},
		{
			id: 20,
			firstName: 'Avery',
			lastName: 'Perez',
			role: RoleOptions.Volunteer,
			email: 'avery@example.com',
			password: 'password456',
			phone: '555-555-5567',
			profilePhoto: '/public/img/profile-pics/woman-25.jpg',
			preferredNumWeeksServing: 2,
			experiences: [23], // IDs of previous experiences
		},
		{
			id: 21,
			firstName: 'Noah',
			lastName: 'Hall',
			role: RoleOptions.Volunteer,
			email: 'noah@example.com',
			password: 'password123',
			preferredNumWeeksServing: 1,
			experiences: [24, 25], // IDs of previous experiences
		},
		{
			id: 22,
			firstName: 'Olivia',
			lastName: 'Wright',
			role: RoleOptions.Volunteer,
			email: 'olivia@example.com',
			password: 'password456',
			phone: '555-555-5568',
			profilePhoto: '/public/img/profile-pics/woman-26.jpg',
			preferredNumWeeksServing: 2,
		},
		{
			id: 23,
			firstName: 'Liam',
			lastName: 'Robinson',
			role: RoleOptions.Volunteer,
			email: 'liam@example.com',
			password: 'password789',
			preferredNumWeeksServing: 1,
			experiences: [26], // IDs of previous experiences
		},
		{
			id: 24,
			firstName: 'Emma',
			lastName: 'Diaz',
			role: RoleOptions.Volunteer,
			email: 'emma@example.com',
			password: 'password890',
			phone: '555-555-5569',
			preferredNumWeeksServing: 3,
			experiences: [27, 28], // IDs of previous experiences
		},
		{
			id: 25,
			firstName: 'Lucas',
			lastName: 'Scott',
			role: RoleOptions.Volunteer,
			email: 'lucas@example.com',
			password: 'password901',
			profilePhoto: '/public/img/profile-pics/man-21.jpg',
			preferredNumWeeksServing: 2,
			experiences: [29], // IDs of previous experiences
		},
		{
			id: 26,
			firstName: 'Ava',
			lastName: 'King',
			role: RoleOptions.Volunteer,
			email: 'ava@example.com',
			password: 'password234',
			phone: '555-555-5570',
			profilePhoto: '/public/img/profile-pics/woman-27.jpg',
			preferredNumWeeksServing: 4,
		},
		{
			id: 27,
			firstName: 'Mason',
			lastName: 'Young',
			role: RoleOptions.Volunteer,
			email: 'mason@example.com',
			password: 'password567',
			profilePhoto: '/public/img/profile-pics/man-22.jpg',
			preferredNumWeeksServing: 2,
			experiences: [30], // IDs of previous experiences
		},
		{
			id: 28,
			firstName: 'Sophia',
			lastName: 'Lopez',
			role: RoleOptions.Volunteer,
			email: 'sophia@example.com',
			password: 'password890',
			phone: '555-555-5571',
			preferredNumWeeksServing: 4,
			experiences: [31, 32], // IDs of previous experiences
		},
		{
			id: 29,
			firstName: 'Jackson',
			lastName: 'Garcia',
			role: RoleOptions.Volunteer,
			email: 'jackson@example.com',
			password: 'password123',
			preferredNumWeeksServing: 1,
			experiences: [33, 34, 35], // IDs of previous experiences
		},
		{
			id: 30,
			firstName: 'Lily',
			lastName: 'Clark',
			role: RoleOptions.Volunteer,
			email: 'lily@example.com',
			password: 'password456',
			phone: '555-555-5572',
			profilePhoto: '/public/img/profile-pics/woman-28.jpg',
			preferredNumWeeksServing: 2,
		},
		{
			id: 31,
			firstName: 'Elijah',
			lastName: 'Turner',
			role: RoleOptions.Volunteer,
			email: 'elijah@example.com',
			password: 'password123',
			profilePhoto: '/public/img/profile-pics/man-23.jpg',
			preferredNumWeeksServing: 1,
			experiences: [36, 37, 38], // IDs of previous experiences
		},
		{
			id: 32,
			firstName: 'Scarlett',
			lastName: 'Hernandez',
			role: RoleOptions.Volunteer,
			email: 'scarlett@example.com',
			password: 'password456',
			phone: '555-555-5573',
			preferredNumWeeksServing: 2,
			experiences: [39], // IDs of previous experiences
		},
		{
			id: 33,
			firstName: 'Benjamin',
			lastName: 'Scott',
			role: RoleOptions.Volunteer,
			email: 'benjamin@example.com',
			password: 'password789',
			profilePhoto: '/public/img/profile-pics/man-24.jpg',
			preferredNumWeeksServing: 1,
			experiences: [40], // IDs of previous experiences
		},
		{
			id: 34,
			firstName: 'Hannah',
			lastName: 'Perez',
			role: RoleOptions.Volunteer,
			email: 'hannah@example.com',
			password: 'password890',
			phone: '555-555-5574',
			preferredNumWeeksServing: 3,
			experiences: [41, 42, 43, 44], // IDs of previous experiences
		},
		{
			id: 35,
			firstName: 'Henry',
			lastName: 'Mitchell',
			role: RoleOptions.Volunteer,
			email: 'henry@example.com',
			password: 'password901',
			profilePhoto: '/public/img/profile-pics/man-25.jpg',
			preferredNumWeeksServing: 2,
			experiences: [45, 46], // IDs of previous experiences
		},
		{
			id: 36,
			firstName: 'Ella',
			lastName: 'Adams',
			role: RoleOptions.Volunteer,
			email: 'ella@example.com',
			password: 'password234',
			phone: '555-555-5575',
			profilePhoto: '/public/img/profile-pics/woman-31.jpg',
			preferredNumWeeksServing: 4,
			experiences: [47], // IDs of previous experiences
		},
		{
			id: 37,
			firstName: 'Samuel',
			lastName: 'Collins',
			role: RoleOptions.Volunteer,
			email: 'samuel@example.com',
			password: 'password567',
			preferredNumWeeksServing: 2,
		},
		{
			id: 38,
			firstName: 'Avery',
			lastName: 'Gonzalez',
			role: RoleOptions.Volunteer,
			email: 'avery@example.com',
			password: 'password890',
			phone: '555-555-5576',
			preferredNumWeeksServing: 4,
		},
		{
			id: 39,
			firstName: 'Daniel',
			lastName: 'Hall',
			role: RoleOptions.Volunteer,
			email: 'daniel@example.com',
			password: 'password123',
			profilePhoto: '/public/img/profile-pics/man-27.jpg',
			preferredNumWeeksServing: 1,
		},
		{
			id: 40,
			firstName: 'Sophie',
			lastName: 'Wright',
			role: RoleOptions.Volunteer,
			email: 'sophie@example.com',
			password: 'password456',
			phone: '555-555-5577',
			profilePhoto: '/public/img/profile-pics/woman-51.jpg',
			preferredNumWeeksServing: 2,
			experiences: [48, 49], // IDs of previous experiences
		},
		{
			id: 41,
			firstName: 'Mason',
			lastName: 'Brown',
			role: RoleOptions.Volunteer,
			email: 'mason@example.com',
			password: 'password123',
			profilePhoto: '/public/img/profile-pics/man-31.jpg',
			preferredNumWeeksServing: 1,
			experiences: [50], // IDs of previous experiences
		},
		{
			id: 42,
			firstName: 'Evelyn',
			lastName: 'Gomez',
			role: RoleOptions.Volunteer,
			email: 'evelyn@example.com',
			password: 'password456',
			phone: '555-555-5578',
			profilePhoto: '/public/img/profile-pics/woman-52.jpg',
			preferredNumWeeksServing: 2,
			experiences: [51, 52], // IDs of previous experiences
		},
		{
			id: 43,
			firstName: 'Liam',
			lastName: 'Reed',
			role: RoleOptions.Volunteer,
			email: 'liam@example.com',
			password: 'password789',
			preferredNumWeeksServing: 1,
			experiences: [53], // IDs of previous experiences
		},
		{
			id: 44,
			firstName: 'Ava',
			lastName: 'Rivera',
			role: RoleOptions.Volunteer,
			email: 'ava@example.com',
			password: 'password890',
			phone: '555-555-5579',
			profilePhoto: '/public/img/profile-pics/woman-53.jpg',
			preferredNumWeeksServing: 3,
			experiences: [54], // IDs of previous experiences
		},
		{
			id: 45,
			firstName: 'William',
			lastName: 'Ward',
			role: RoleOptions.Volunteer,
			email: 'william@example.com',
			password: 'password901',
			profilePhoto: '/public/img/profile-pics/man-32.jpg',
			preferredNumWeeksServing: 2,
			experiences: [55, 56], // IDs of previous experiences
		},
		{
			id: 46,
			firstName: 'Olivia',
			lastName: 'Morgan',
			role: RoleOptions.Volunteer,
			email: 'olivia@example.com',
			password: 'password234',
			phone: '555-555-5580',
			preferredNumWeeksServing: 4,
			experiences: [57, 58, 59], // IDs of previous experiences
		},
		{
			id: 47,
			firstName: 'James',
			lastName: 'Johnson',
			role: RoleOptions.Volunteer,
			email: 'james@example.com',
			password: 'password567',
			profilePhoto: '/public/img/profile-pics/man-33.jpg',
			preferredNumWeeksServing: 2,
		},
		{
			id: 48,
			firstName: 'Sophia',
			lastName: 'Parker',
			role: RoleOptions.Volunteer,
			email: 'sophia@example.com',
			password: 'password890',
			phone: '555-555-5581',
			profilePhoto: '/public/img/profile-pics/woman-55.jpg',
			preferredNumWeeksServing: 4,
			experiences: [60, 61], // IDs of previous experiences
		},
		{
			id: 49,
			firstName: 'Michael',
			lastName: 'Harris',
			role: RoleOptions.Volunteer,
			email: 'michael@example.com',
			password: 'password123',
			preferredNumWeeksServing: 1,
			experiences: [62], // IDs of previous experiences
		},
		{
			id: 50,
			firstName: 'Charlotte',
			lastName: 'Martin',
			role: RoleOptions.Volunteer,
			email: 'charlotte@example.com',
			password: 'password456',
			phone: '555-555-5582',
			preferredNumWeeksServing: 2,
			experiences: [63, 64, 65], // IDs of previous experiences
		},
		{
			id: 51,
			firstName: 'Liam',
			lastName: 'Perez',
			role: RoleOptions.Volunteer,
			email: 'liam@example.com',
			password: 'password123',
			profilePhoto: '/public/img/profile-pics/man-34.jpg',
			preferredNumWeeksServing: 1,
		},
		{
			id: 52,
			firstName: 'Olivia',
			lastName: 'Garcia',
			role: RoleOptions.Volunteer,
			email: 'olivia@example.com',
			password: 'password456',
			phone: '555-555-5583',
			profilePhoto: '/public/img/profile-pics/woman-56.jpg',
			preferredNumWeeksServing: 2,
			experiences: [66], // IDs of previous experiences
		},
		{
			id: 53,
			firstName: 'Ethan',
			lastName: 'Mitchell',
			role: RoleOptions.Volunteer,
			email: 'ethan@example.com',
			password: 'password789',
			profilePhoto: '/public/img/profile-pics/man-35.jpg',
			preferredNumWeeksServing: 1,
			experiences: [67, 68, 69], // IDs of previous experiences
		},
		{
			id: 54,
			firstName: 'Chloe',
			lastName: 'Turner',
			role: RoleOptions.Volunteer,
			email: 'chloe@example.com',
			password: 'password890',
			phone: '555-555-5584',
			profilePhoto: '/public/img/profile-pics/woman-62.jpg',
			preferredNumWeeksServing: 3,
			experiences: [70, 71], // IDs of previous experiences
		},
		{
			id: 55,
			firstName: 'Daniel',
			lastName: 'Hall',
			role: RoleOptions.Volunteer,
			email: 'daniel@example.com',
			password: 'password901',
			preferredNumWeeksServing: 2,
			experiences: [72], // IDs of previous experiences
		},
		{
			id: 56,
			firstName: 'Sophia',
			lastName: 'Hernandez',
			role: RoleOptions.Volunteer,
			email: 'sophia@example.com',
			password: 'password234',
			phone: '555-555-5585',
			preferredNumWeeksServing: 4,
			experiences: [73], // IDs of previous experiences
		},
		{
			id: 57,
			firstName: 'Jackson',
			lastName: 'Ward',
			role: RoleOptions.Volunteer,
			email: 'jackson@example.com',
			password: 'password567',
			profilePhoto: '/public/img/profile-pics/man-36.jpg',
			preferredNumWeeksServing: 2,
			experiences: [74], // IDs of previous experiences
		},
		{
			id: 58,
			firstName: 'Ava',
			lastName: 'Morgan',
			role: RoleOptions.Volunteer,
			email: 'ava@example.com',
			password: 'password890',
			phone: '555-555-5586',
			profilePhoto: '/public/img/profile-pics/woman-88.jpg',
			preferredNumWeeksServing: 4,
		},
		{
			id: 59,
			firstName: 'William',
			lastName: 'Johnson',
			role: RoleOptions.Volunteer,
			email: 'william@example.com',
			password: 'password123',
			profilePhoto: '/public/img/profile-pics/man-37.jpg',
			preferredNumWeeksServing: 1,
			experiences: [75, 76, 77, 78, 79], // IDs of previous experiences
		},
		{
			id: 60,
			firstName: 'Emma',
			lastName: 'Parker',
			role: RoleOptions.Volunteer,
			email: 'emma@example.com',
			password: 'password456',
			phone: '555-555-5587',
			profilePhoto: '/public/img/profile-pics/woman-97.jpg',
			preferredNumWeeksServing: 2,
			experiences: [80], // IDs of previous experiences
		},
	],
	experiences: [],
};

export default DB;
